import type { MuscleGroup } from './types';

/**
 * Exercise suggestions per muscle group — shown when a region is focused on
 * the body map. Names double as taggable tokens: tapping one appends it to the
 * check-in note, tapping again removes it, so the note stays the single source
 * of truth for what was actually done.
 *
 * Ten per group, ordered compound-first — the order they'd be programmed in.
 */
export const EXERCISES: Record<MuscleGroup, string[]> = {
  chest: [
    'Bench Press',
    'Incline DB Press',
    'Weighted Dips',
    'Incline Bench',
    'DB Bench Press',
    'Cable Fly',
    'Pec Deck',
    'Machine Press',
    'Push-ups',
    'Decline Press',
  ],
  back: [
    'Deadlift',
    'Pull-ups',
    'Barbell Row',
    'Lat Pulldown',
    'Seated Cable Row',
    'T-Bar Row',
    'Single-Arm DB Row',
    'Chest-Supported Row',
    'Straight-Arm Pulldown',
    'Rack Pull',
  ],
  shoulders: [
    'Overhead Press',
    'DB Shoulder Press',
    'Lateral Raise',
    'Arnold Press',
    'Face Pulls',
    'Rear Delt Fly',
    'Cable Lateral Raise',
    'Front Raise',
    'Upright Row',
    'Machine Press',
  ],
  biceps: [
    'Barbell Curl',
    'Incline DB Curl',
    'Hammer Curl',
    'Preacher Curl',
    'Chin-ups',
    'Cable Curl',
    'Concentration Curl',
    'EZ-Bar Curl',
    'Spider Curl',
    'Reverse Curl',
  ],
  triceps: [
    'Close-Grip Bench',
    'Skullcrushers',
    'Rope Pushdown',
    'Overhead Extension',
    'Dips',
    'Cable Kickback',
    'JM Press',
    'Diamond Push-ups',
    'Bar Pushdown',
    'French Press',
  ],
  core: [
    'Hanging Leg Raise',
    'Cable Crunch',
    'Ab Wheel',
    'Plank',
    'Pallof Press',
    'Russian Twist',
    'Dead Bug',
    'Side Plank',
    'V-ups',
    'Dragon Flag',
  ],
  quads: [
    'Back Squat',
    'Front Squat',
    'Leg Press',
    'Split Squat',
    'Leg Extension',
    'Hack Squat',
    'Goblet Squat',
    'Walking Lunge',
    'Step-ups',
    'Sissy Squat',
  ],
  hamstrings: [
    'Romanian Deadlift',
    'Lying Leg Curl',
    'Good Mornings',
    'Nordic Curl',
    'Seated Leg Curl',
    'Stiff-Leg Deadlift',
    'Glute-Ham Raise',
    'Single-Leg RDL',
    'Cable Pull-Through',
    'Back Extension',
  ],
  glutes: [
    'Hip Thrust',
    'Sumo Deadlift',
    'Cable Kickback',
    'Walking Lunge',
    'Step-ups',
    'Bulgarian Split Squat',
    'Glute Bridge',
    'Abduction Machine',
    'Frog Pumps',
    'Curtsy Lunge',
  ],
  calves: [
    'Standing Calf Raise',
    'Seated Calf Raise',
    'Donkey Calf Raise',
    'Single-Leg Raise',
    'Leg Press Calf Raise',
    'Smith Calf Raise',
    'Jump Rope',
    'Farmer Walk on Toes',
    'Box Jumps',
    'Tibialis Raise',
  ],
};
