import type { MuscleGroup } from './types';

/**
 * Exercise demonstration frames (start/end position), bundled from the
 * public-domain free-exercise-db (unlicense.org) — resized to 420px.
 * Keys are catalog names; a muscle-qualified key wins when the same name
 * means different movements (e.g. Cable Kickback for triceps vs glutes).
 */
// prettier-ignore
const MEDIA: Record<string, number[]> = {
  "Ab Wheel": [require('../assets/exercises/ab-roller-0.jpg'), require('../assets/exercises/ab-roller-1.jpg')],
  "Abduction Machine": [require('../assets/exercises/thigh-abductor-0.jpg'), require('../assets/exercises/thigh-abductor-1.jpg')],
  "Arnold Press": [require('../assets/exercises/arnold-dumbbell-press-0.jpg'), require('../assets/exercises/arnold-dumbbell-press-1.jpg')],
  "Back Extension": [require('../assets/exercises/hyperextensions-back-extensions-0.jpg'), require('../assets/exercises/hyperextensions-back-extensions-1.jpg')],
  "Back Squat": [require('../assets/exercises/barbell-squat-0.jpg'), require('../assets/exercises/barbell-squat-1.jpg')],
  "Bar Pushdown": [require('../assets/exercises/triceps-pushdown-0.jpg'), require('../assets/exercises/triceps-pushdown-1.jpg')],
  "Barbell Curl": [require('../assets/exercises/barbell-curl-0.jpg'), require('../assets/exercises/barbell-curl-1.jpg')],
  "Barbell Row": [require('../assets/exercises/bent-over-barbell-row-0.jpg'), require('../assets/exercises/bent-over-barbell-row-1.jpg')],
  "Bench Press": [require('../assets/exercises/barbell-bench-press-medium-grip-0.jpg'), require('../assets/exercises/barbell-bench-press-medium-grip-1.jpg')],
  "Box Jumps": [require('../assets/exercises/front-box-jump-0.jpg'), require('../assets/exercises/front-box-jump-1.jpg')],
  "Bulgarian Split Squat": [require('../assets/exercises/one-leg-barbell-squat-0.jpg'), require('../assets/exercises/one-leg-barbell-squat-1.jpg')],
  "Cable Crunch": [require('../assets/exercises/cable-crunch-0.jpg'), require('../assets/exercises/cable-crunch-1.jpg')],
  "Cable Curl": [require('../assets/exercises/standing-biceps-cable-curl-0.jpg'), require('../assets/exercises/standing-biceps-cable-curl-1.jpg')],
  "Cable Fly": [require('../assets/exercises/cable-crossover-0.jpg'), require('../assets/exercises/cable-crossover-1.jpg')],
  "Cable Lateral Raise": [require('../assets/exercises/cable-seated-lateral-raise-0.jpg'), require('../assets/exercises/cable-seated-lateral-raise-1.jpg')],
  "Cable Pull-Through": [require('../assets/exercises/pull-through-0.jpg'), require('../assets/exercises/pull-through-1.jpg')],
  "Chest-Supported Row": [require('../assets/exercises/lying-t-bar-row-0.jpg'), require('../assets/exercises/lying-t-bar-row-1.jpg')],
  "Chin-ups": [require('../assets/exercises/chin-up-0.jpg'), require('../assets/exercises/chin-up-1.jpg')],
  "Close-Grip Bench": [require('../assets/exercises/close-grip-barbell-bench-press-0.jpg'), require('../assets/exercises/close-grip-barbell-bench-press-1.jpg')],
  "Concentration Curl": [require('../assets/exercises/concentration-curls-0.jpg'), require('../assets/exercises/concentration-curls-1.jpg')],
  "Curtsy Lunge": [require('../assets/exercises/dumbbell-rear-lunge-0.jpg'), require('../assets/exercises/dumbbell-rear-lunge-1.jpg')],
  "DB Bench Press": [require('../assets/exercises/dumbbell-bench-press-0.jpg'), require('../assets/exercises/dumbbell-bench-press-1.jpg')],
  "DB Shoulder Press": [require('../assets/exercises/dumbbell-shoulder-press-0.jpg'), require('../assets/exercises/dumbbell-shoulder-press-1.jpg')],
  "Dead Bug": [require('../assets/exercises/dead-bug-0.jpg'), require('../assets/exercises/dead-bug-1.jpg')],
  "Deadlift": [require('../assets/exercises/barbell-deadlift-0.jpg'), require('../assets/exercises/barbell-deadlift-1.jpg')],
  "Decline Press": [require('../assets/exercises/decline-barbell-bench-press-0.jpg'), require('../assets/exercises/decline-barbell-bench-press-1.jpg')],
  "Diamond Push-ups": [require('../assets/exercises/push-ups-close-triceps-position-0.jpg'), require('../assets/exercises/push-ups-close-triceps-position-1.jpg')],
  "Dips": [require('../assets/exercises/dips-triceps-version-0.jpg'), require('../assets/exercises/dips-triceps-version-1.jpg')],
  "Donkey Calf Raise": [require('../assets/exercises/donkey-calf-raises-0.jpg'), require('../assets/exercises/donkey-calf-raises-1.jpg')],
  "EZ-Bar Curl": [require('../assets/exercises/ez-bar-curl-0.jpg'), require('../assets/exercises/ez-bar-curl-1.jpg')],
  "Face Pulls": [require('../assets/exercises/face-pull-0.jpg'), require('../assets/exercises/face-pull-1.jpg')],
  "Farmer Walk on Toes": [require('../assets/exercises/farmer-s-walk-0.jpg'), require('../assets/exercises/farmer-s-walk-1.jpg')],
  "French Press": [require('../assets/exercises/seated-triceps-press-0.jpg'), require('../assets/exercises/seated-triceps-press-1.jpg')],
  "Frog Pumps": [require('../assets/exercises/butt-lift-bridge-0.jpg'), require('../assets/exercises/butt-lift-bridge-1.jpg')],
  "Front Raise": [require('../assets/exercises/front-dumbbell-raise-0.jpg'), require('../assets/exercises/front-dumbbell-raise-1.jpg')],
  "Front Squat": [require('../assets/exercises/front-barbell-squat-0.jpg'), require('../assets/exercises/front-barbell-squat-1.jpg')],
  "Glute Bridge": [require('../assets/exercises/butt-lift-bridge-0.jpg'), require('../assets/exercises/butt-lift-bridge-1.jpg')],
  "Glute-Ham Raise": [require('../assets/exercises/glute-ham-raise-0.jpg'), require('../assets/exercises/glute-ham-raise-1.jpg')],
  "Goblet Squat": [require('../assets/exercises/goblet-squat-0.jpg'), require('../assets/exercises/goblet-squat-1.jpg')],
  "Good Mornings": [require('../assets/exercises/good-morning-0.jpg'), require('../assets/exercises/good-morning-1.jpg')],
  "Hack Squat": [require('../assets/exercises/hack-squat-0.jpg'), require('../assets/exercises/hack-squat-1.jpg')],
  "Hammer Curl": [require('../assets/exercises/hammer-curls-0.jpg'), require('../assets/exercises/hammer-curls-1.jpg')],
  "Hanging Leg Raise": [require('../assets/exercises/hanging-leg-raise-0.jpg'), require('../assets/exercises/hanging-leg-raise-1.jpg')],
  "Hip Thrust": [require('../assets/exercises/barbell-hip-thrust-0.jpg'), require('../assets/exercises/barbell-hip-thrust-1.jpg')],
  "Incline Bench": [require('../assets/exercises/barbell-incline-bench-press-medium-grip-0.jpg'), require('../assets/exercises/barbell-incline-bench-press-medium-grip-1.jpg')],
  "Incline DB Curl": [require('../assets/exercises/incline-dumbbell-curl-0.jpg'), require('../assets/exercises/incline-dumbbell-curl-1.jpg')],
  "Incline DB Press": [require('../assets/exercises/incline-dumbbell-press-0.jpg'), require('../assets/exercises/incline-dumbbell-press-1.jpg')],
  "JM Press": [require('../assets/exercises/jm-press-0.jpg'), require('../assets/exercises/jm-press-1.jpg')],
  "Jump Rope": [require('../assets/exercises/rope-jumping-0.jpg'), require('../assets/exercises/rope-jumping-1.jpg')],
  "Lat Pulldown": [require('../assets/exercises/wide-grip-lat-pulldown-0.jpg'), require('../assets/exercises/wide-grip-lat-pulldown-1.jpg')],
  "Lateral Raise": [require('../assets/exercises/side-lateral-raise-0.jpg'), require('../assets/exercises/side-lateral-raise-1.jpg')],
  "Leg Extension": [require('../assets/exercises/leg-extensions-0.jpg'), require('../assets/exercises/leg-extensions-1.jpg')],
  "Leg Press": [require('../assets/exercises/leg-press-0.jpg'), require('../assets/exercises/leg-press-1.jpg')],
  "Leg Press Calf Raise": [require('../assets/exercises/calf-press-on-the-leg-press-machine-0.jpg'), require('../assets/exercises/calf-press-on-the-leg-press-machine-1.jpg')],
  "Lying Leg Curl": [require('../assets/exercises/lying-leg-curls-0.jpg'), require('../assets/exercises/lying-leg-curls-1.jpg')],
  "Nordic Curl": [require('../assets/exercises/natural-glute-ham-raise-0.jpg'), require('../assets/exercises/natural-glute-ham-raise-1.jpg')],
  "Overhead Extension": [require('../assets/exercises/triceps-overhead-extension-with-rope-0.jpg'), require('../assets/exercises/triceps-overhead-extension-with-rope-1.jpg')],
  "Overhead Press": [require('../assets/exercises/standing-military-press-0.jpg'), require('../assets/exercises/standing-military-press-1.jpg')],
  "Pallof Press": [require('../assets/exercises/pallof-press-0.jpg'), require('../assets/exercises/pallof-press-1.jpg')],
  "Pec Deck": [require('../assets/exercises/butterfly-0.jpg'), require('../assets/exercises/butterfly-1.jpg')],
  "Plank": [require('../assets/exercises/plank-0.jpg'), require('../assets/exercises/plank-1.jpg')],
  "Preacher Curl": [require('../assets/exercises/preacher-curl-0.jpg'), require('../assets/exercises/preacher-curl-1.jpg')],
  "Pull-ups": [require('../assets/exercises/pullups-0.jpg'), require('../assets/exercises/pullups-1.jpg')],
  "Push-ups": [require('../assets/exercises/pushups-0.jpg'), require('../assets/exercises/pushups-1.jpg')],
  "Rack Pull": [require('../assets/exercises/rack-pulls-0.jpg'), require('../assets/exercises/rack-pulls-1.jpg')],
  "Rear Delt Fly": [require('../assets/exercises/seated-bent-over-rear-delt-raise-0.jpg'), require('../assets/exercises/seated-bent-over-rear-delt-raise-1.jpg')],
  "Reverse Curl": [require('../assets/exercises/reverse-barbell-curl-0.jpg'), require('../assets/exercises/reverse-barbell-curl-1.jpg')],
  "Romanian Deadlift": [require('../assets/exercises/romanian-deadlift-0.jpg'), require('../assets/exercises/romanian-deadlift-1.jpg')],
  "Rope Pushdown": [require('../assets/exercises/triceps-pushdown-rope-attachment-0.jpg'), require('../assets/exercises/triceps-pushdown-rope-attachment-1.jpg')],
  "Russian Twist": [require('../assets/exercises/russian-twist-0.jpg'), require('../assets/exercises/russian-twist-1.jpg')],
  "Seated Cable Row": [require('../assets/exercises/seated-cable-rows-0.jpg'), require('../assets/exercises/seated-cable-rows-1.jpg')],
  "Seated Calf Raise": [require('../assets/exercises/seated-calf-raise-0.jpg'), require('../assets/exercises/seated-calf-raise-1.jpg')],
  "Seated Leg Curl": [require('../assets/exercises/seated-leg-curl-0.jpg'), require('../assets/exercises/seated-leg-curl-1.jpg')],
  "Side Plank": [require('../assets/exercises/side-bridge-0.jpg'), require('../assets/exercises/side-bridge-1.jpg')],
  "Single-Arm DB Row": [require('../assets/exercises/one-arm-dumbbell-row-0.jpg'), require('../assets/exercises/one-arm-dumbbell-row-1.jpg')],
  "Single-Leg Raise": [require('../assets/exercises/dumbbell-seated-one-leg-calf-raise-0.jpg'), require('../assets/exercises/dumbbell-seated-one-leg-calf-raise-1.jpg')],
  "Sissy Squat": [require('../assets/exercises/weighted-sissy-squat-0.jpg'), require('../assets/exercises/weighted-sissy-squat-1.jpg')],
  "Skullcrushers": [require('../assets/exercises/ez-bar-skullcrusher-0.jpg'), require('../assets/exercises/ez-bar-skullcrusher-1.jpg')],
  "Smith Calf Raise": [require('../assets/exercises/smith-machine-calf-raise-0.jpg'), require('../assets/exercises/smith-machine-calf-raise-1.jpg')],
  "Spider Curl": [require('../assets/exercises/spider-curl-0.jpg'), require('../assets/exercises/spider-curl-1.jpg')],
  "Split Squat": [require('../assets/exercises/split-squats-0.jpg'), require('../assets/exercises/split-squats-1.jpg')],
  "Standing Calf Raise": [require('../assets/exercises/standing-calf-raises-0.jpg'), require('../assets/exercises/standing-calf-raises-1.jpg')],
  "Step-ups": [require('../assets/exercises/barbell-step-ups-0.jpg'), require('../assets/exercises/barbell-step-ups-1.jpg')],
  "Stiff-Leg Deadlift": [require('../assets/exercises/stiff-legged-barbell-deadlift-0.jpg'), require('../assets/exercises/stiff-legged-barbell-deadlift-1.jpg')],
  "Straight-Arm Pulldown": [require('../assets/exercises/straight-arm-pulldown-0.jpg'), require('../assets/exercises/straight-arm-pulldown-1.jpg')],
  "Sumo Deadlift": [require('../assets/exercises/sumo-deadlift-0.jpg'), require('../assets/exercises/sumo-deadlift-1.jpg')],
  "T-Bar Row": [require('../assets/exercises/t-bar-row-with-handle-0.jpg'), require('../assets/exercises/t-bar-row-with-handle-1.jpg')],
  "Upright Row": [require('../assets/exercises/upright-barbell-row-0.jpg'), require('../assets/exercises/upright-barbell-row-1.jpg')],
  "V-ups": [require('../assets/exercises/jackknife-sit-up-0.jpg'), require('../assets/exercises/jackknife-sit-up-1.jpg')],
  "Walking Lunge": [require('../assets/exercises/barbell-walking-lunge-0.jpg'), require('../assets/exercises/barbell-walking-lunge-1.jpg')],
  "chest/Machine Press": [require('../assets/exercises/machine-bench-press-0.jpg'), require('../assets/exercises/machine-bench-press-1.jpg')],
  "chest/Weighted Dips": [require('../assets/exercises/dips-chest-version-0.jpg'), require('../assets/exercises/dips-chest-version-1.jpg')],
  "glutes/Cable Kickback": [require('../assets/exercises/one-legged-cable-kickback-0.jpg'), require('../assets/exercises/one-legged-cable-kickback-1.jpg')],
  "shoulders/Machine Press": [require('../assets/exercises/machine-shoulder-military-press-0.jpg'), require('../assets/exercises/machine-shoulder-military-press-1.jpg')],
  "triceps/Cable Kickback": [require('../assets/exercises/tricep-dumbbell-kickback-0.jpg'), require('../assets/exercises/tricep-dumbbell-kickback-1.jpg')],
};

/** Frames for an exercise, muscle-qualified first. Empty array = no media. */
export function exerciseMedia(name: string, muscle?: MuscleGroup): number[] {
  if (muscle) {
    const qualified = MEDIA[`${muscle}/${name}`];
    if (qualified) return qualified;
  }
  return MEDIA[name] ?? [];
}
